#!/bin/bash

# Deployment configuration for slova-sveltekit
# Generated by server-setup.sh

# Server configuration
SERVER_HOST="116.203.18.8"
SERVER_USER="ondrejrohon"
APP_NAME="slova-sveltekit"
DEPLOY_PATH="/app"

# Application configuration
APP_PORT="4173"
HEALTH_CHECK_URL="http://localhost:4173/api/health"

# Database configuration
DB_HOST="localhost"
DB_PORT="5432"
DB_NAME="slova_production"
DB_USER="slova_user"
DB_PASS="somepass"

# Timeouts
HEALTH_CHECK_TIMEOUT="30"
APP_START_TIMEOUT="10"

# Backup configuration
KEEP_BACKUPS="2"

# SSH options
SSH_OPTIONS="-o ConnectTimeout=10 -o BatchMode=yes"

# PM2 configuration
PM2_SCRIPT="bun"
PM2_ARGS="run preview"
