#!/bin/bash

# Interactive deployment configuration setup
# This script prompts for deployment settings and saves them as .env.production

set -e

echo "🚀 Slova SvelteKit Deployment Configuration Setup"
echo "=================================================="
echo ""

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " input
        if [ -z "$input" ]; then
            input="$default"
        fi
    else
        read -p "$prompt: " input
    fi
    
    eval "$var_name=\"$input\""
}

# Function to prompt for password (hidden input)
prompt_password() {
    local prompt="$1"
    local var_name="$2"
    
    read -s -p "$prompt: " input
    echo ""
    eval "$var_name=\"$input\""
}

# Get current values from deploy.config.local.sh if it exists
if [ -f "../deploy.config.local.sh" ]; then
    echo "📖 Found existing configuration, using as defaults..."
    echo ""
    
    # Extract current values
    CURRENT_SERVER_HOST=$(grep '^SERVER_HOST=' ../deploy.config.local.sh | cut -d'"' -f2)
    CURRENT_SERVER_USER=$(grep '^SERVER_USER=' ../deploy.config.local.sh | cut -d'"' -f2)
    CURRENT_APP_NAME=$(grep '^APP_NAME=' ../deploy.config.local.sh | cut -d'"' -f2)
    CURRENT_DEPLOY_PATH=$(grep '^DEPLOY_PATH=' ../deploy.config.local.sh | cut -d'"' -f2)
    CURRENT_APP_PORT=$(grep '^APP_PORT=' ../deploy.config.local.sh | cut -d'"' -f2)
    CURRENT_DB_NAME=$(grep '^DB_NAME=' ../deploy.config.local.sh | cut -d'"' -f2)
    CURRENT_DB_PASS=$(grep '^DB_PASS=' ../deploy.config.local.sh | cut -d'"' -f2)
fi

# Interactive prompts
echo "🔧 Server Configuration"
echo "----------------------"
prompt_with_default "Server host (IP address)" "$CURRENT_SERVER_HOST" "SERVER_HOST"
prompt_with_default "Server username" "$CURRENT_SERVER_USER" "SERVER_USER"
prompt_with_default "Application name" "$CURRENT_APP_NAME" "APP_NAME"
prompt_with_default "Deployment path" "$CURRENT_DEPLOY_PATH" "DEPLOY_PATH"

echo ""
echo "🌐 Application Configuration"
echo "---------------------------"
prompt_with_default "Application port" "$CURRENT_APP_PORT" "APP_PORT"

echo ""
echo "🗄️  Database Configuration"
echo "-------------------------"
prompt_with_default "Database name" "$CURRENT_DB_NAME" "DB_NAME"
prompt_password "Database password" "DB_PASS"

echo ""
echo "📝 Generating .env.production file..."
echo ""

# Create .env.production file
cat > .env.production << EOF
# Slova SvelteKit Production Environment
# Generated by setup-env.sh on $(date)

# Server Configuration
SERVER_HOST=$SERVER_HOST
SERVER_USER=$SERVER_USER
APP_NAME=$APP_NAME
DEPLOY_PATH=$DEPLOY_PATH

# Application Configuration
APP_PORT=$APP_PORT

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=slova_user
DB_PASS=$DB_PASS
EOF

echo "✅ .env.production file created successfully!"
echo ""
echo "📋 Configuration Summary:"
echo "   Server: $SERVER_USER@$SERVER_HOST"
echo "   App: $APP_NAME (port $APP_PORT)"
echo "   Deploy path: $DEPLOY_PATH"
echo "   Database: $DB_NAME"
echo ""
echo "🔒 The .env.production file contains sensitive information."
echo "   Make sure it's added to .gitignore and kept secure."
echo ""
echo "🚀 You can now use this configuration for deployment." 